[clients]
client1 ansible_host=3.252.146.45 ansible_user=cloud_user ansible_ssh_private_key_file=~/.ssh/id_rsa
client2 ansible_host=54.216.167.3 ansible_user=cloud_user ansible_ssh_private_key_file=~/.ssh/id_rsa
client2 ansible_host=3.252.242.78 ansible_user=cloud_user ansible_ssh_private_key_file=~/.ssh/id_rsa

