[clients]
client1 ansible_host=192.168.1.101 ansible_user=cloud_user ansible_ssh_private_key_file=~/.ssh/id_rsa
client2 ansible_host=192.168.1.102 ansible_user=cloud_user ansible_ssh_private_key_file=~/.ssh/id_rsa
client2 ansible_host=192.168.1.103 ansible_user=cloud_user ansible_ssh_private_key_file=~/.ssh/id_rsa

